### ISSUE TITLE
Block dropped on first destroy

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#19]
When a protected block is destroyed by a player it drops an item the first time. This should not happen until the last destroy before the object is removed from the game world.

**Comment by ghost** [comment]
I figured the reason for this out last night. Chx had it so that when you place a reinforced block, there is a 20s delay before the block is marked as reinforced. This makes sense to me now, because if you're building something, you don't want to have to destroy it X times if you place a block wrong. Now, there's still a bug because when a reinforced block is broken, it cancels that pending task and gives the player back their reinforcement material, regardless of whether that pending task ran (causing the block to become officially fortified).

**Comment by Freenor** [comment]
If we accomplished all database interaction with the I/O buffer idea described in other threads, then we could simple comb through it swiftly in RAM and pre-empt it from getting written to the database.  If this is the case, no extra materials should be released from the map upon destruction (if I understand this properly).

**Comment by ghost** [comment]
Fixed in d5f93dff
