### ISSUE TITLE
Citadel in Serious need of PistionPerformance overhaul 

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#58]
[take a look at this](http://dl.dropbox.com/u/21042334/Citadel.zip) just run the nolagg.jar and load up the .exam file with it. Citadel's piston retract event is the single largest cause of server lag atm by at least a factor of 10. This error is critical.

**Comment by TheJDz** [comment]
I don't have (and would prefer not to install) Eclipse or any Java IDE on my work PC but I would like to help out with this.  Could you C&P what code executes on the piston retraction event?  Or better yet (since I haven't touched Java since college) pseudocode?

**Comment by ghost** [comment]
There doesn't seem to be anything wrong with this function, I wonder if it's just being called a lot because there are lots of pistons retracting?

```
    @EventHandler(ignoreCancelled = true, priority = EventPriority.HIGH)
    public void pistonRetract(BlockPistonRetractEvent bpre) {
        Block piston = bpre.getBlock();
        BlockState state = piston.getState();
        MaterialData data = state.getData();
        BlockFace direction = null;

        // Check the block it pushed directly
        if (data instanceof PistonBaseMaterial) {
            direction = ((PistonBaseMaterial) data).getFacing();
        }

        if (direction == null)
            return;

        // the block that the piston moved
        Block moved = piston.getRelative(direction, 2);

        AccessDelegate delegate = AccessDelegate.getDelegate(moved);
        Reinforcement reinforcement = delegate.getReinforcement();

        if (reinforcement != null) {
            bpre.setCancelled(true);
        }
    }
```

**Comment by TheJDz** [comment]
Thanks!  My guess is still a database optimization issue.  It explains why the lag just gets worse as time goes on, despite most of the same code being used since Citadel started.  Is this the first time a profiler was run?  It'd be interesting to compare to a past one.  ANYWAY, I hate make you find and C&P shit for me, but I'm going to ask anyway.  Can I see the "getReinforcement" code?  I'm about to head out to lunch but I'll be back in an hour or so.  I'm curious to see how the reinforcement table is queried as well as what indexes are on it.

**Comment by ghost** [comment]
You can view the code on GitHub: https://github.com/Exultant/Citadel/blob/master/src/com/untamedears/citadel/

I don't think it's a database optimization issue, otherwise why would pistonExtend (which can check MULTIPLE blocks, not just one) take so much less time than retract? I wonder exactly what happens when the event is cancelled? Does it immediately try to retract again?

**Comment by ghost** [comment]
Oh, I just noticed that pistonExtend has this check, while pistonRetract does not...

```
if (block.getType() == Material.AIR){
    break;
}
```

Which means that when a piston extends but does not push a block, the database is not hit (though IIRC, it all should be cached anyway), but when that piston retracts, it does do a lookup.

**Comment by ghost** [comment]
BTW, BlockPistonRetractEvent has a getDirection() function, which could render getting piston state and piston material data unnecessary. It probably won't dramatically improve performance, but it would cut the amount of code in this function by half.

**Comment by intangir** [comment]
I think fnord is onto something, it probably tests retract every tick.. it
should instead retract without the connected block. Also does it
differentiate between stick and unsticky?

**Comment by TheJDz** [comment]
It does seem like something is fishy here.  Between the two, Extend should take longer because they do the exact same thing except Extend checks all blocks that are about to be moved (so potentially up to 12?) where Retract would always check one and one only.  It makes me wonder if the profiler data means what I interpretted it to mean.  That is, the average single call of pistonRetract is longer than the average single call of pistonExtract.  The only way I can see that being true is a lot of pistons pushing air, which saves a getReinforcement call.  If so, we can add (as recommended above) a few checks in pistonRetract.

I'd recommend first to see if the piston is a normal non-sticky piston, because if it's non-sticky I don't see a reason to even check for reinforcement at all.  I may not understand the code in context, so correct me if I'm wrong.

Second, if it is a sticky piston, check if the block in question is any of the following:
Air, obsidian, bedrock, End portal, and Nether portal (blocks that pistons can't move, according to minecraft wiki.  I'm not sure how air is normally treated however)

Also, we should consider checking if it's any block that cannot be reinforced, such as water and lava.  Really, anything that can't normally be pushed by a piston and anything that can't be reinforced.

**Comment by intangir** [comment]
Check how many times it is actually called, it could be called every tick
on cancels

I think fnord is right. Also it doesn't check if its even a sticky piston
