### ISSUE TITLE
Groups assigned new names, protections possibly not transferring correctly from previous versions of Citadel

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#65]
An old copy of the main server sql db is on the test server for this exact purpose, at the moment it seems to show users to log in are using a different group than their existing default group in the database.

For example my new default group is 'ttk21' I have been unable to test if I still have access to the protections in the group 'ttk2' but from the way I understand the code that is unlikely. At the moment this is the only major bug found in testing of the latest ram caching patch.

**Comment by remyroy** [comment]
Citadel uses the player name as returned from org.bukkit.entity.Player.getName() or org.bukkit.entity.Player.getDisplayName() as the name of the default personal group. From my testing on my personal server, I've seen bukkit plugins that changed the return value from those methods in some way which made it difficult for me to test citadel as I had the same problem (previous protections were on a different default group which was now different). In my case, the specific plugin that changed the name of the player was part of Essentials Core.

Have you tried removing all the other plugin just to check that this is not the case? If this is the case, you might want to try and remove plugins in a bisect way to find out which one is the culprit.

**Comment by JonnyD** [comment]
The reason a group was created called "ttk21" was because you didn't have a Default Group and group name "ttk2" was already taken. The reason for this is because Groups and Reinforcements are too tightly coupled in the database. Because Citadel 2.0 has the ability to delete groups, deleting one group would delete all the reinforcements associated with that group so I introduced a Default Group which prevented the user from accidently deleting all his reinforcements and which only holds private reinforcements. Once a group is deleted those reinforcements would go back to his Default Group as private reinforcements.

**Comment by ttk2** [comment]
for anyone testing on this issue, I have a fresh copy of the production servers sql databases sitting in sqldump.sql in the testing folder, simply use restoresql.sh to restore the testing database to its original conditon and test to see if new changes stil  create duplicate groups.

**Comment by JonnyD** [comment]
Are you sure they are duplicate groups? Read my comment above and also check the personal group table to see if it's a personal group created. See Citadel 1.0 had groups half implemented but reinforcements were assigned to the player's username. Citadel 2.0 came along and had to implement multiple groups, the problem was it couldn't use the players group from Citadel 1.0 as default group because this group had members and group reinforcements. So Citadel 2.0 we create a default group which only holds private (and sometimes public) reinforcements.

**Comment by uncorr** [comment]
Deleting "cxschx1" from personal groups results in "cxschx2" being created.  Even if no reinforcements with a group of "cxschx2" are entered into the reinforcement database, deleting "cxschx2" results in a group called "cxschx3" being created.

I've traced the source of the problem to the Ebeanserver query in CitadelDao.findPersonalGroup( String ).  Even though the parameter given is correct, the query returns the incorrect group.

Wouldn't it be much easier to just assume personal groups will have the same name and owner as the user and no password and just get it over with?  If people are able to log onto Civcraft and spoof their names, then we've got bigger problems.

**Comment by JonnyD** [comment]
"Wouldn't it be much easier to just assume personal groups will have the same name and owner as the user and no password and just get it over with?"

Say if I play on the server and you never did but I knew you were planning on doing it in the future and let's say I created a group called "cxshx". You then join the server and because your name was already taken how would the code know what your personal group is?

**Comment by uncorr** [comment]
That gave me an idea as to the nature of the appendations.

It turns out that if you don't own a personal group, when the ebeanserver creates one for you, if there's a pre-existing group with your name in it in the main factions list, then the ebeanserver appends a "1" to your name.  This mistake is present in prod, and what it means is that people who made a reinforcement before v2 will get "1"s appended to their personal group names during migration, while people who joined after will have a personal group the same as their name.

This behavior may seem weird, but the more I think about it, the more harmless it seems.  It's just the same as if in fact the scenario JonnyD described above happened.  Since there haven't been any explosions on prod, my advice would be to just not poke sleeping dragons in the eye and try to "fix" this.

I move to resolve as "won't fix"
